In [2]:
#Live Demo
#Start, Stop, and Step Parameters to the built-in slice function
import numpy as np

a = np.arange(10)
s = slice(2,7,2)
print(a[s])

[2 4 6]


In [3]:
import numpy as np

a = np.arange(10)
b = a[2:7:2]
print (b)
print (a)

[2 4 6]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Slice single item
import numpy as np

a=np.arange(10)
b=a[5]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [6]:
# Slice items starting from index
import numpy as np
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [7]:
# Slice items between indexes
import numpy as np

a = np.arange(10)
print (a[2:5])

[2 3 4]


In [8]:
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

#Slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [1]:
# Array to begin with
import numpy as np
a=np.array([[1,2,3],[3,4,5,],[4,5,6]])

print('Our Array is :')
print(a)
print('\n')

#This returns array of items in the second column
print('The items in the second column are:')
print(a[...,1])
print('\n')

#Now we will slice all items from the second row
print('The items in the second row are:')
print(a[1,...])
print('\n')

#Now we will slice all items from column 1 onwards
print('The items column 1 onwards are:')
print(a[...,1:])

Our Array is :
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
